sudo: required

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t dominikriha/react-test ./client

script:
  - docker run -e CI=true dominikriha/react-test npm run test

after_success:
  - docker build -t dominikriha/multi-client ./client
  - docker build -t dominikriha/multi-nginx ./nginx
  - docker build -t dominikriha/multi-server ./server
  - docker build -t dominikriha/multi-worker ./worker
  # Push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dominikriha/multi-client
  - docker push dominikriha/multi-nginx
  - docker push dominikriha/multi-server
  - docker push dominikriha/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-860791175306"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
